node("productization") {
    cleanWs()

    def profileId = params.PROFILE_ID
    def imageVersion = params.IMAGE_VERSION
    def clusterServiceVersion = params.CLUSTER_SERVICE_VERSION
    def upstreamBranch = params.UPSTREAM_BRANCH

	checkout([
		$class: 'GitSCM', branches: [[name: '*/master']],
		userRemoteConfigs: [[url: 'https://github.com/VaishnaviR18/fuse-camel-k12.git']]
	])

    stage("build") {
		sh "${workspace}/fuse-camel-k12.git/update-settings-xml.sh ${profileId} ${imageVersion} ${clusterServiceVersion} ${upstreamBranch}  | tee build.log"
	}

    cleanWs()
}
